spring:
  application:
    name: nginx_post_request
  profiles:
    active: local 
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:~/test
    platform: h2
    schema: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: none